spring.application.name=sitesChecker

bot.name=AvocadoForMashaBot
bot.token=${TELEGRAM_BOT_TOKEN}

bot.checkEnergy=true
bot.checkTheFuture=true

bot.myChatId=358906883
bot.husbandsChatId=428123860

bot.textToFind=2027