spring.application.name=sitesChecker

bot.name=AvocadoForMashaBot
bot.token=${TELEGRAM_BOT_TOKEN}

bot.checkEnergy=true
bot.checkTheFuture=true

bot.myChatId=358906883
bot.husbandsChatId=428123860

bot.chatId=358906883,428123860

bot.scheduler.interval = 600000

bot.textToFind=27