spring.application.name=sitesChecker

bot.name=AvocadoForMashaBot
bot.token=${TELEGRAM_BOT_TOKEN}

bot.url=https://xn--80acgdf0a1ag2aob6b6a.xn--p1ai/irkutsk/

bot.myChatId=358906883
bot.husbandsChatId=428123860

bot.chatId=358906883,428123860

bot.scheduler.interval = 600000

bot.textToFind=\u043C\u0435\u0441\u0442\u0430